<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* replacement for hook_menu */
function hello_menu_menu() {

  /* localhost:8080/drupal/hello */
  /* 'hello' is the key in the drupal path */
  $items['hello'] = array(
    'title' => 'Hello World',  /* note: not translated */
    'page callback' => 'hello_menu_simple_hello',  /* function to call */
    'access arguments' => array('access content'), /* corresponds to 'View Published Content' */
    'menu_name' => 'main-menu', /* by default, gets added by default to navigation menu */
    'weight' => 1,  /* otherwise, by default, this puts it left of Home in Main menu */
  );
  
  $items['variables'] = array(
    'title' => 'Hello Variables',
    'page callback' => 'hello_menu_list_variables',
    'access arguments' => array('access content'),
   # 'menu_name' => 'main-menu', /* by default, gets added by default to navigation menu */
    'menu_name' => 'navigation', /* put it back into navigation instead of main-menu */
   # 'weight' => 2,  /* otherwise, by default, this puts it left of Home in Main menu */
  );
  
  /* submenu under variables, specific for site_name */
  /*
  $items['variables/site_name'] = array(
    'title' => 'Hello Variables: Site Name',
    'page callback' => 'hello_menu_show_variables',
    'access arguments' => array('access content'),
    'menu_name' => 'main-menu',
    'weight' => 3,
  );
  */

  /* use % for dynamic page name */
  /* array for title and page arguments is:
   * 0: variables
   * 1: wildcard value from the %
   */
  $items['variables/%'] = array(
    'title callback' => 'hello_menu_show_variable_title',
    'title arguments' => array(1),  /* sends parameter to the title callback */
    'page callback' => 'hello_menu_show_variable',
    'page arguments' => array(1), /* sends parameter to page callback */
    'access arguments' => array('access content'),
   # 'menu_name' => 'main-menu', /* by default, gets added by default to navigation menu */
    'menu_name' => 'navigation',
   # 'weight' => 3,  /* otherwise, by default, this puts it left of Home in Main menu */
  );
  
  return $items;
}

/* NOTE: start your function names with your module name */
/* this must return a string */

/* just print hello */
function hello_menu_simple_hello() {
  return t('Hello world!!!');
}

/* list the variables */
function hello_menu_list_variables() {
  $variables = variable_initialize(); /* get all variables into array */
  $names = array_keys ($variables);
  $output = '<ul>'; /* start unordered list in HTML */
  
  /* dpm ($variables); */  /* this makes it appear at top */  
  /* return t('TESTING!!'); */ /* just returns the string */
  /* return(kpr ($variables, TRUE));  */ /* this makes it appear in main section */
  /* return(kpr ($names, TRUE)); * /* returns just variable names */
  
  foreach ($names as $name) {
    $output .= '<li>' . $name . '</li>';
  }
  $output .= "</ul>"; /* close unordered list */
  return ($output);
}

/* works with specific variable: site_name */
function hello_menu_show_variables() {
  $value = variable_get('site_name', t('No value for this variable'));
  return ($value);
}

/* get variable name as a parameter */
function hello_menu_show_variable($variable_name) {
  $value = variable_get($variable_name, t('No value for this variable'));
  return ($value);
}

/* callback for title with parameter */
function hello_menu_show_variable_title($variable_name) {
  return t('Show Variable: @name', array('@name' => $variable_name));
}